### ISSUE TITLE
Fatal error when trying to load an image that does not exists

### ISSUE THREAD

**Issue by miyoyo** [Firew0lf/ctruLua#1]
Done with Citra HEAD-d8908ae
### Steps to reproduce error
 * Put the main.lua and the example.lua in citra/user/sdmc/3ds/ctruLua
 * Launch ctruLua.3dsx
 * Launch example.lua
 * If no "icon.png" file is present, citra *crashes*

**Comment by Firew0lf** [comment]
Fixed, `gfx.texture.load()` now return `nil` if the file is not found.
